name: Java Build

on:
  push:
    #branches: [ "main", "dapclarke-actiondemo-1" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  pull-requests: read # allows SonarQube to decorate PRs with analysis results

jobs:
  Build_and_Test_in_Development_Slot:
    runs-on: ubuntu-latest

    permissions:
      issues: write

    env:
      APP_RESOURCE_GROUP: AppServiceRG
      APP_NAME: javacicdtest-wa
      PROJECT_PATH: projects/maven/rest-service-dctest
        
    steps:      

      - name: Check out repository
        uses: actions/checkout@v5

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: |
          cd projects/maven/rest-service-dctest
          mvn clean package -Dtest=!GreetingApiControllerTests
        #run: mvn -B package --file pom.xml
        #working-directory: my-app-path          


      # REF: https://learn.microsoft.com/en-us/azure/azure-resource-manager/bicep/deploy-github-actions?tabs=CLI%2Cuserlevel
      - name: Log into Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Bicep file
        uses: azure/arm-deploy@v1
        with:
          scope: 'resourcegroup'
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ env.APP_RESOURCE_GROUP }}
          template: ${{ env.PROJECT_PATH }}/bicep/webapp.bicep
          parameters: >
            ${{ env.PROJECT_PATH }}/bicep/webapp.parameters.json
            appName=${{ env.APP_NAME }}
          failOnStdErr: false

      - name: Get webapp config - publish profile + hostname
        id: publishingProfile
        uses: azure/cli@v1
        with:
          inlineScript: |
            profile=$(az webapp deployment list-publishing-profiles --name ${{ env.APP_NAME }} --resource-group ${{ env.APP_RESOURCE_GROUP }} --xml)
            echo "profile=$profile" >> $GITHUB_OUTPUT
            hostname=$(az webapp show --name ${{ env.APP_NAME }} --resource-group ${{ env.APP_RESOURCE_GROUP }} --query defaultHostName -o tsv)
            echo "hostname=$hostname" >> $GITHUB_OUTPUT
            developmentprofile=$(az webapp deployment list-publishing-profiles --name ${{ env.APP_NAME }} --slot development --resource-group ${{ env.APP_RESOURCE_GROUP }} --xml)
            echo "developmentprofile=$developmentprofile" >> $GITHUB_OUTPUT            
            developmentslothostname=$(az webapp show --name ${{ env.APP_NAME }} --slot development --resource-group ${{ env.APP_RESOURCE_GROUP }} --query hostNames -o tsv)
            echo "developmenthostname=$developmentslothostname" >> $GITHUB_OUTPUT

      #- name: Use variables
      #  run: |
      #    echo "Output variable : ${{ steps.publishingProfile.outputs.profile }}"

      - name: Deploy to Azure Web App (development slot)
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.APP_NAME }}
          slot-name: 'development'  # desired slot name
          publish-profile: ${{ steps.publishingProfile.outputs.developmentprofile }}
          package: ${{ env.PROJECT_PATH }}/target/*.jar

      - name: Wait for deployment to stabilize
        run: |
          sleep 30  # Give the app some time to start up properly

      - name: Run REST Assured Tests
        env:
          APP_URL: https://${{ steps.publishingProfile.outputs.hostname }}
          DEV_SLOT_APP_URL: https://${{ steps.publishingProfile.outputs.developmenthostname }}
        run: |
          cd ${{ env.PROJECT_PATH }}
          # Run only the API tests
          mvn test -Dtest=GreetingApiControllerTests -DAPP_BASE_URL=$DEV_SLOT_APP_URL

      - name: ZAP Scan
        uses: zaproxy/action-api-scan@v0.9.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          format: openapi
          #target: 'https://testrestapi-gcefhdbrgdddced4.uksouth-01.azurewebsites.net/greeting'
          target: "https://${{ steps.publishingProfile.outputs.developmenthostname }}/greeting"
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: GreetingApp-JAR
          path: ${{ env.PROJECT_PATH }}/target/*.jar
      
      - name: Get Date
        id: get-date
        run: |
          echo "date=$(/bin/date -u "+%Y%m%d")" >> $GITHUB_OUTPUT
        shell: bash

      - uses: actions/cache@v4
        with:
          path: ${{ env.PROJECT_PATH }}/target/*.jar
          key: WebApp-${{ steps.get-date.outputs.date }}-${{ hashFiles("${{ env.PROJECT_PATH }}/target/*.jar") }}
      
  #Deploy_and_Test_in_Staging_Slot:
    