name: Java Build

on:
  push:
    #branches: [ "main", "dapclarke-actiondemo-1" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  pull-requests: read # allows SonarQube to decorate PRs with analysis results

jobs:
  CI_CD_Java_Maven_Azure_WebApp:
    runs-on: ubuntu-latest

    permissions:
      issues: write

    env:
      APP_RESOURCE_GROUP: AppServiceRG
      APP_NAME: dunc-rest-service-dctesttmp
      PROJECT_PATH: projects/maven/rest-service-dctest
        
    steps:      

      - name: Check out repository
        uses: actions/checkout@v5

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: |
          cd projects/maven/rest-service-dctest
          mvn clean package -Dtest=!GreetingApiControllerTests
        #run: mvn -B package --file pom.xml
        #working-directory: my-app-path          


      # REF: https://learn.microsoft.com/en-us/azure/azure-resource-manager/bicep/deploy-github-actions?tabs=CLI%2Cuserlevel
      - name: Log into Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Bicep file
        uses: azure/arm-deploy@v1
        with:
          scope: 'resourcegroup'
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ env.APP_RESOURCE_GROUP }}
          template: ${{ env.PROJECT_PATH }}/bicep/webapp.bicep
          parameters: ${{ env.PROJECT_PATH }}/bicep/webapp.parameters.json
          failOnStdErr: false
          #parameters: 'storagePrefix=mystore storageSKU=Standard_LRS'

      - name: Get webapp config - publish profile + hostname
        id: publishingProfile
        uses: azure/cli@v1
        with:
          inlineScript: |
            profile=$(az webapp deployment list-publishing-profiles --name ${{ env.APP_NAME }} --resource-group ${{ env.APP_RESOURCE_GROUP }} --xml)
            echo "profile=$profile" >> $GITHUB_OUTPUT
            hostname=$(az webapp show --name ${{ env.APP_NAME }} --resource-group ${{ env.APP_RESOURCE_GROUP }} --query defaultHostName -o tsv)
            echo "hostname=$hostname" >> $GITHUB_OUTPUT

      #- name: Use variables
      #  run: |
      #    echo "Output variable : ${{ steps.publishingProfile.outputs.profile }}"

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.APP_NAME }} #${{ secrets.AZURE_WEBAPP_NAME }}
          #publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          publish-profile: ${{ steps.publishingProfile.outputs.profile }}
          package: ${{ env.PROJECT_PATH }}/target/*.jar  # or .war depending on your packaging

      - name: Wait for deployment to stabilize
        run: |
          sleep 10  # Give the app some time to start up properly

      - name: Run REST Assured Tests
        env:
          APP_URL: https://${{ steps.publishingProfile.outputs.hostname }}
        run: |
          cd ${{ env.PROJECT_PATH }}
          # Run only the API tests
          mvn test -Dtest=GreetingApiControllerTests -DAPP_BASE_URL=$APP_URL

      - name: ZAP Scan
        uses: zaproxy/action-api-scan@v0.9.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          format: openapi
          #target: 'https://testrestapi-gcefhdbrgdddced4.uksouth-01.azurewebsites.net/greeting'
          target: "https://${{ steps.publishingProfile.outputs.hostname }}/greeting"
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: GreetingApp-JAR
          path: ${{ env.PROJECT_PATH }}/target/*.jar